apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-test
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      containers:
        - name: devops-test
          image: guddnr5345/devops-test:24
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-test-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: devops-test
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007  # 나중에 localhost:30007로 접속